version: '3.7'
services:
  feasibility-db:
    image: 'postgres:13.1-alpine'
    container_name: feasibility-db
    ports:
    - ${CODEX_FEASIBILITY_BACKEND_DATABASE_PORT:-5432}:5432
    environment:
      - POSTGRES_USER=codex-postgres
      - POSTGRES_PASSWORD=codex-password
      - POSTGRES_DB=codex_ui
